### ISSUE TITLE
Problem with some JS plugins

### ISSUE THREAD

**Issue by gneuman** [deviodigital/cleanblog#10]
I installed the theme but have problems with 2 plugins

ThriveLeads and Gravity Forms, both of them don't show up in the theme but in the HTML I can see it

Saludos

**Comment by walidmahade** [comment]
The owner will claim , the problem is in the plugins, and the plugins owner will claim that the problem is with the themes.
If its urgent, you could try hiring a developer.

**Comment by robertdevore** [comment]
When you are on the page where the plugins should be working, what do you see when you view the the console in your browser? Are there any specific errors that are popping up?

**Comment by gneuman** [comment]
The problem is that they Don't show in the browser. But in the inspector they sre running like they never started the JS

Saludos

**Comment by robertdevore** [comment]
If there aren't any errors that show up, I'm not sure how much help I can be. Is the URL live? I can look at it myself and see if I can notice anything.

**Comment by gneuman** [comment]
I had changed theme and turn off the plugin

Let me turn on and put the theme. It will be life in 5 minuteS

Saludos

Gabriel Neuman

**Comment by gneuman** [comment]
Robert the problem is with the blog post; There is where the gravityforms don't show

On a regular Page they still showing on

Blog post: [http://gabrielneuman.com/calcula-valor-vida-cliente/](url) (Not Showing)
Page: [http://gabrielneuman.com/contacto/](url) (Showing)

**Comment by robertdevore** [comment]
I looked in the source, and I see the Gravity Forms code but with an inline style of `display: none;`

Here's a link with more information about it - [link](https://www.gravityhelp.com/forums/topic/forms-not-showing-2)

**Comment by gneuman** [comment]
Look what I found [https://www.gravityhelp.com/question/why-is-there-a-style-attribute-of-displaynone-being-added-my-form-isnt-showing-up/](url)

**Comment by robertdevore** [comment]
That's not it, see the footer.php file [here](https://github.com/deviodigital/cleanblog/blob/master/footer.php#L41)
